name: Build and Deploy .NET 9 Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install .NET 9 Preview SDK
      run: |
        wget https://dotnetcli.azureedge.net/dotnet/Sdk/9.0.100-preview.1.24123.4/dotnet-sdk-9.0.100-preview.1.24123.4-linux-x64.tar.gz
        mkdir -p $HOME/dotnet9
        tar -zxf dotnet-sdk-9.0.100-preview.1.24123.4-linux-x64.tar.gz -C $HOME/dotnet9
        echo "$HOME/dotnet9" >> $GITHUB_PATH
        echo "DOTNET_ROOT=$HOME/dotnet9" >> $GITHUB_ENV

    - name: Confirm SDK version
      run: dotnet --version

    - name: Restore dependencies
      run: dotnet restore Lab13_BernieOrtiz.sln

    - name: Build
      run: dotnet build Lab13_BernieOrtiz.sln --configuration Release

    - name: Publish
      run: dotnet publish Lab13_BernieOrtiz.API/Lab13_BernieOrtiz.API.csproj --configuration Release --output ./published

    - name: Done
      run: echo "✅ Publicación finalizada con .NET 9"
