name: Build and Deploy .NET 9 Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install .NET 9 manually
      run: |
        wget https://dotnetcli.azureedge.net/dotnet/Sdk/9.0.100-preview.1.24123.4/dotnet-sdk-9.0.100-preview.1.24123.4-linux-x64.tar.gz
        mkdir -p $HOME/dotnet9
        tar zxf dotnet-sdk-9.0.100-preview.1.24123.4-linux-x64.tar.gz -C $HOME/dotnet9
        echo "$HOME/dotnet9" >> $GITHUB_PATH
        echo "DOTNET_ROOT=$HOME/dotnet9" >> $GITHUB_ENV


    - name: Check .NET version
      run: dotnet --version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --output ./published
